# http://www.appveyor.com/docs/appveyor-yml
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "5"
    - nodejs_version: "4"

# Allow failing jobs for bleeding-edge Node.js versions.
matrix:
  allow_failures:
    - nodejs_version: "0.10"
    - nodejs_version: "5"

# Install scripts. (runs after repo cloning)
install:
  # Install all dependencies
  - npm install

# Post-install test scripts.
test_script:
  - cmd: npm test
